### ISSUE TITLE
Hyperlinks to naming conventions and guidance on naming and tagging not working

### ISSUE THREAD

**Issue by kreisdenker** [MicrosoftDocs/cloud-adoption-framework.de-de#1]
The Hyperlinks to the articles of naming conventions and guidance on naming and tagging are not working anymore.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b1fc82b5-34a5-ec62-85bf-aa3f6b365827
* Version Independent ID: a6fd18dc-0536-06e5-86b9-ff99ff58f3c2
* Content: [Effizientes Organisieren Ihrer Azure-Ressourcen - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/de-de/azure/cloud-adoption-framework/ready/azure-setup-guide/organize-resources?tabs=NamingStandards#feedback)
* Content Source: [docs/ready/azure-setup-guide/organize-resources.md](https://github.com/MicrosoftDocs/cloud-adoption-framework.de-de/blob/live/docs/ready/azure-setup-guide/organize-resources.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @laraaleite
* Microsoft Alias: **kfollis**

**Comment by SunnyDeng** [comment]
@kreisdenker Thank you for the feedback. Can you please check again? In the current de-de version of  Effizientes Organisieren Ihrer Azure-Ressourcen - Microsoft Cloud Adoption Framework for Azure, there are two links: Benennungsregeln und Einschränkungen and  Anleitung zu Benennung und Tagging , all works for me. So i am closing this ISSUE. Please feel free to reactivate if you still have questions.
